# Generated by Django 4.1.4 on 2023-01-04 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='company',
            field=models.CharField(default='Glacier', max_length=50, null=True),
        ),
    ]
