# Generated by Django 4.1.4 on 2023-01-05 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0002_employee_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('user', models.CharField(max_length=50)),
                ('entry', models.CharField(max_length=50)),
                ('lbreak', models.CharField(max_length=50)),
                ('exit', models.CharField(max_length=50)),
            ],
        ),
    ]
