# Generated by Django 4.1.4 on 2023-01-06 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0005_alter_attendance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='exit',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='user',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
