# Generated by Django 4.1.5 on 2023-01-06 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0009_attendance_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='location',
            new_name='start_location',
        ),
        migrations.AddField(
            model_name='attendance',
            name='stop_location',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
