# Generated by Django 4.1.5 on 2023-01-10 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('day', models.CharField(max_length=50, null=True)),
                ('user', models.CharField(max_length=50, null=True)),
                ('entry', models.CharField(max_length=50)),
                ('lbreak1', models.CharField(max_length=50, null=True)),
                ('lbreak2', models.CharField(max_length=50, null=True)),
                ('exit', models.CharField(max_length=50, null=True)),
                ('hour', models.CharField(max_length=50, null=True)),
                ('start_location', models.CharField(max_length=500, null=True)),
                ('stop_location', models.CharField(max_length=500, null=True)),
            ],
        ),
    ]
