# Generated by Django 4.1.4 on 2023-01-13 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0007_alter_attendance_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(auto_created=True, null=True),
        ),
    ]
