# Generated by Django 4.1.4 on 2023-01-16 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0009_alter_attendance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='date_approved',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
