# Generated by Django 4.1.4 on 2023-01-19 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0011_trackattendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackattendance',
            name='btn1',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='trackattendance',
            name='btn2',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='trackattendance',
            name='btn3',
            field=models.BooleanField(null=True),
        ),
    ]
