# Generated by Django 4.1.4 on 2023-02-08 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0012_alter_trackattendance_btn1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='days',
            field=models.IntegerField(default=None),
        ),
    ]
