# Generated by Django 4.1.4 on 2023-02-08 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0018_alter_leavetype_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavetype',
            name='name',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
