# Generated by Django 4.1.4 on 2023-03-03 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0024_alter_leavetype_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='type',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
