# Generated by Django 4.1.4 on 2023-02-01 08:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tasktype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TaskType', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='worklog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User', models.CharField(max_length=255)),
                ('Date', models.DateField(default=django.utils.timezone.now)),
                ('Workdone', models.CharField(max_length=255)),
                ('Hours', models.PositiveIntegerField(default=0)),
                ('Billable', models.BooleanField(default=False, null=True, verbose_name='Billable')),
                ('TaskType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp_worklog.tasktype')),
            ],
        ),
    ]
