# Generated by Django 4.1.4 on 2023-02-01 08:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Project', '0001_initial'),
        ('emp_worklog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worklog',
            name='project_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Project.subproject'),
        ),
        migrations.AlterField(
            model_name='worklog',
            name='TaskType',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='emp_worklog.tasktype'),
        ),
        migrations.AlterField(
            model_name='worklog',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
