# Generated by Django 4.1.4 on 2023-02-22 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0002_subproject_hours_done'),
        ('emp_worklog', '0002_worklog_project_id_alter_worklog_tasktype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worklog',
            name='TaskType',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='emp_worklog.tasktype'),
        ),
        migrations.AlterField(
            model_name='worklog',
            name='project_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Project.subproject'),
        ),
    ]
