# Generated by Django 4.1.4 on 2023-02-22 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Issue', '0002_alter_ticket_assigned_grp_alter_ticket_assigned_to_and_more'),
        ('emp_worklog', '0003_alter_worklog_tasktype_alter_worklog_project_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='worklog',
            name='task',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Issue.ticket'),
        ),
    ]
