# Generated by Django 4.1.4 on 2023-02-25 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='companyEmployee',
            new_name='employee',
        ),
    ]
