# Generated by Django 4.1.4 on 2023-02-01 05:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('customer', models.CharField(max_length=250)),
                ('estimate_hr', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('worked_hr', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('details', models.CharField(max_length=500, null=True)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('estimated_date', models.DateField(null=True)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('details', models.CharField(max_length=500, null=True)),
                ('hour', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project.project')),
            ],
        ),
    ]
