# Generated by Django 4.1.4 on 2023-03-03 09:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Authentication', '0006_usedetails'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='useDetails',
            new_name='userDetails',
        ),
    ]
