# Generated by Django 4.2.2 on 2023-07-10 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0007_rename_usedetails_userdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='mrequest',
            field=models.BooleanField(default=False, null=True, verbose_name='Request'),
        ),
    ]
