# Generated by Django 4.2.2 on 2023-07-10 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0008_userdetails_mrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='ismanager',
            field=models.BooleanField(default=False, null=True, verbose_name='Manager'),
        ),
    ]
