# Generated by Django 4.2.2 on 2023-07-10 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0009_userdetails_ismanager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='ismanager',
        ),
    ]
