# Generated by Django 4.2.2 on 2023-07-13 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0010_remove_userdetails_ismanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='loggeduser',
            name='device',
            field=models.CharField(default='before', max_length=200),
        ),
    ]
