# Generated by Django 4.2.2 on 2023-07-21 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0012_manager_role_userroles_usermanager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermanager',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Authentication.userdetails'),
        ),
        migrations.DeleteModel(
            name='Manager',
        ),
    ]
