# Generated by Django 4.2.2 on 2023-07-21 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0013_alter_usermanager_manager_delete_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='is_manager',
            field=models.BooleanField(default=False, null=True, verbose_name='Manager'),
        ),
    ]
