# Generated by Django 4.1.4 on 2023-08-01 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0014_userdetails_is_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='is_mfa',
            field=models.BooleanField(default=False, null=True, verbose_name='MFA'),
        ),
    ]
