# Generated by Django 4.1.4 on 2023-02-21 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_name', models.CharField(max_length=30)),
                ('ticket_type', models.CharField(max_length=30)),
                ('short_desc', models.CharField(max_length=130)),
                ('open_date', models.DateField(auto_now=True)),
                ('affected_user', models.CharField(max_length=30)),
                ('priority', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('assigned_grp', models.CharField(max_length=30)),
                ('assigned_to', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=100)),
                ('comments', models.CharField(max_length=120)),
            ],
        ),
    ]
