# Generated by Django 4.1.4 on 2023-02-22 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Issue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='assigned_grp',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='assigned_to',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='comments',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='short_desc',
            field=models.CharField(max_length=130, null=True),
        ),
    ]
