# Generated by Django 4.2.2 on 2023-07-03 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Issue', '0004_alter_ticket_affected_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ticketDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(max_length=500, null=True)),
                ('date', models.DateField(auto_now=True)),
                ('ticket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Issue.ticket')),
            ],
        ),
    ]
