# Generated by Django 4.2.2 on 2023-07-03 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Issue', '0005_ticketdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketdetails',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
