# Generated by Django 4.2.2 on 2023-07-03 06:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Issue', '0006_alter_ticketdetails_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketdetails',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
