# Generated by Django 4.2.2 on 2023-07-06 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Issue', '0007_ticketdetails_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='state',
            field=models.CharField(default='New', max_length=30),
        ),
    ]
