# Generated by Django 4.2.2 on 2023-07-06 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Issue', '0008_alter_ticket_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='state',
            field=models.CharField(default='New', max_length=30, null=True),
        ),
    ]
