# Generated by Django 4.2.2 on 2023-07-14 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0011_loggeduser_device'),
        ('Issue', '0009_alter_ticket_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='compnay',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Authentication.company'),
        ),
    ]
