# Generated by Django 4.2.2 on 2023-07-14 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Issue', '0010_ticket_compnay'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='compnay',
            new_name='company',
        ),
    ]
