# Generated by Django 4.2.2 on 2023-07-14 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Issue', '0011_rename_compnay_ticket_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='last_updated',
            field=models.DateField(null=True),
        ),
    ]
