# Generated by Django 4.2.2 on 2023-07-14 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Issue', '0012_alter_ticket_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='open_date',
            field=models.DateField(null=True),
        ),
    ]
