# Generated by Django 4.2.2 on 2023-07-14 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Issue', '0013_alter_ticket_open_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='last_updated',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
