# Generated by Django 4.1.4 on 2023-01-23 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='initialpassword',
            name='first_changed',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='initialpassword',
            name='first_password',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
