# Generated by Django 4.1.4 on 2023-07-29 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Manager', '0004_remove_teams_lead_teams_description_teamusers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, null=True)),
                ('date1', models.DateField(default=django.utils.timezone.now)),
                ('date2', models.DateField(default=django.utils.timezone.now)),
                ('task_type', models.CharField(max_length=100, null=True)),
                ('log_type', models.CharField(max_length=100, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
